- name: Publish Report 
        # continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report ChromeLinux
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
